config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'songs#index'

  resources :artists 

    resources :songs do
    resources :charts, only: [:index, :new, :create, :destroy]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :charts, dependent: :destroy
    has_many :songs, through: :charts
end

app/models/chart.rb
class Chart < ApplicationRecord
    belongs_to :artist
    belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :charts, dependent: :destroy
  has_many :artist, through: :charts

  def spotify_link
    spotify_link = self.spotify.slice! 'https://open.spotify.com/track/'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artist = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new(artist_params)
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def edit
  end


  def destroy
    @artist.destroy
    redirect_to artists_path
  end


private
  def artist_params
    params.require(:artist).permit(:name)
  end 

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_song

  def index
    @charts = Chart.all
  end

  def new
    @artists = Artist.all - @song.artists
    @chart = @song.charts.new
    render partial: 'form'
  end
  
  # def show
  #   @chart = Chart.find(params[:id])
  # end

  def create
    @chart = @song.charts.new(chart_params)

    if @chart.save
      redirect_to song_charts_path(@song)
    else
      render :new
    end
  end

  # def edit
  #   @chart = Chart.find(params[:id])
  # end

  # def update
  #   @chart = Chart.find(params[:id])

  #   if @chart.update(chart_params)
  #     redirect_to chart_path
  #   else 
  #     render :edit  
  #   end
  # end

  def destroy
    @chart = @song.charts.find(params[:id])
    @chart.destroy
    redirect_to song_charts_path(@song)
  end

  private
  def chart_params
  params.require(:chart).permit(:title, :genre)
  end


  def set_song
    @song = Song.find(params[:song_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  validates :spotify, {slice! 'https://open.spotify.com/track/'}

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Songs.new
    render partial: 'form'
  end


  def create
    @song = Songs.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title, :artist, :album, :genre, :spotify)
  end

  def set_song
    @song = Song.find(params[:id])
  end 


  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper

end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for [@song, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :label %>
  <%= f.text_field :label, required: true %>
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/charts/_form.index.html.erb
<h1>Add a Chart</h1>
<h1> <%= @chart.id ? 'Edit Chart' : 'Create Chart'%> </h1>

<%= form_for @chart do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <%= f.submit%>
<% end%>


<hr>

<button>
<%= link_to 'Cancel', root_path%>
</button>

app/views/charts/edit.html.erb
<h1>Add a chart</h1>
<h1><%= @chart.id ? 'Edit Chart' : 'Create Chart'%> </h1>

<%= form_for @chart do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <%= f.submit%>
<% end%>


<hr>

<button>
<%= link_to 'Cancel', root_path%>
</button>

app/views/charts/index.html.erb
<div class="chart-header">
<h1>Charts TOP 100</h1>

</div>
<%= link_to 'Artist Index', artists_path %>


<div class="chart">
<div class="row">
<div class="col"></div>
<div class="col-10">
<ul>
  <% @charts.each do |chart|%>
    <li class="card mb-3"><%= link_to chart.title, chart_path(chart) %></li>
  <% end %>
</ul>

</div>
<div class="col"></div>
</div>
</div>

<div class="chart-footer">
<%= link_to 'New Chart', new_chart_path %>
</div>

app/views/charts/new.html.erb
<h1>Add a chart</h1>
<h1><%= @chart.id ? 'Edit chart' : 'Create chart'%> </h1>

<%= form_for @chart do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <%= f.submit%>
<% end%>


<hr>

<button>
<%= link_to 'Cancel', root_path%>
</button>

app/views/charts/show.html.erb
<div class="chart-header">
<h1>Title: <%= @chart.title %></h1>
<h1>Genre: <%= @chart.genre %></h1>
</div>

<div class="chart">
<div class="row">
<div class="col"></div>
<div class="col-10">

<ol id="columns">
  <% @artist.songs.each do |song|%>
    <li class="card chart-song mb-3 column" draggable="true">

    <div class="row">

        <div class="col-2">
        <h1 class="chart-song-position"> <%= song.id %> </h1>
        </div>

            <div class=row>
                <div class="col">
                <h4 class="chart-song-title"><%= song.title %> <br> <%= song.artist %>  </h4> <br> Album: <%= song.album %> <br> Genre: <%= song.genre %> 
                </div>
            </div>

         <div class="col">
            <div class="spotify">
<iframe src="https://open.spotify.com/embed/track/<%= song.spotify %>" width="200" height="280" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>
          <p class="chart-song-edit"> <%= link_to '✎', [@chart, song] %> 〓 </p>
         </div>
    </div>

    </li>
  <% end %>
</ol>



</div>j
<div class="col"></div>
</div>
</div>

<p>What do you like to do?</p>
<p>
<%= link_to 'Add Song', new_chart_song_path(@chart) %> |
<%= link_to 'Edit Chart', edit_chart_path(@chart) %> |
<%= link_to 'Delete Chart', @chart, method: :delete %> |
<%= link_to 'Back', root_path%>
</p>

<script>
var dragSrcEl = null;

function handleDragStart(e) {
  // Target (this) element is the source node.
  dragSrcEl = this;

  e.dataTransfer.effectAllowed = 'move';
  e.dataTransfer.setData('text/html', this.outerHTML);

  this.classList.add('dragElem');
}
function handleDragOver(e) {
  if (e.preventDefault) {
    e.preventDefault(); // Necessary. Allows us to drop.
  }
  this.classList.add('over');

  e.dataTransfer.dropEffect = 'move';  // See the section on the DataTransfer object.

  return false;
}

function handleDragEnter(e) {
  // this / e.target is the current hover target.
}

function handleDragLeave(e) {
  this.classList.remove('over');  // this / e.target is previous target element.
}

function handleDrop(e) {
  // this/e.target is current target element.

  if (e.stopPropagation) {
    e.stopPropagation(); // Stops some browsers from redirecting.
  }

  // Don't do anything if dropping the same column we're dragging.
  if (dragSrcEl != this) {
    // Set the source column's HTML to the HTML of the column we dropped on.
    //alert(this.outerHTML);
    //dragSrcEl.innerHTML = this.innerHTML;
    //this.innerHTML = e.dataTransfer.getData('text/html');
    this.parentNode.removeChild(dragSrcEl);
    var dropHTML = e.dataTransfer.getData('text/html');
    this.insertAdjacentHTML('beforebegin',dropHTML);
    var dropElem = this.previousSibling;
    addDnDHandlers(dropElem);
    
  }
  this.classList.remove('over');
  return false;
}

function handleDragEnd(e) {
  // this/e.target is the source node.
  this.classList.remove('over');

  /*[].forEach.call(cols, function (col) {
    col.classList.remove('over');
  });*/
}

function addDnDHandlers(elem) {
  elem.addEventListener('dragstart', handleDragStart, false);
  elem.addEventListener('dragenter', handleDragEnter, false)
  elem.addEventListener('dragover', handleDragOver, false);
  elem.addEventListener('dragleave', handleDragLeave, false);
  elem.addEventListener('drop', handleDrop, false);
  elem.addEventListener('dragend', handleDragEnd, false);

}

var cols = document.querySelectorAll('#columns .column');
[].forEach.call(cols, addDnDHandlers);


</script>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<h1 class="page-header">Spotify Demo</h1>
<%= form_tag preformers_path, method: "get", html: { class: "form" } do %>
 <div class="form-group col-xs-4">
   <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
 </div>
 <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="jquery-3.4.1.min.js"></script>
    <title>Charts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_for [@chart, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :artist %>
  <%= f.text_field :artist, required: true %>
  <br />
  <%= f.label :album %>
  <%= f.text_field :album, required: true %>
  <br />

  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>

  <%= f.label :spotify %>
  <%= f.text_field :spotify, required: true%>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_for [@chart, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :artist %>
  <%= f.text_field :artist, required: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<div class="chart-header">
<h1><%= @chart.title %></h1>
<h1>Song Details</h1>
</div>

<div class="card mb-3">
<p> Chart Position: <%= @song.id %></p>
<p>Title: <%= @song.title %></p>
<p>Artist: <%= @song.artist %> </p>
<p>Album: <%= @song.album %></p>
<p>Genre: <%= @song.genre %></p>
</div>


<p>
<%= link_to 'View Artist Details', song_preformer_path(@song) %> |
<%= link_to 'Edit Artist Details', new_song_preformer_path(@song) %> |
<%= link_to 'Edit Song', edit_chart_song_path([@chart, @song]) %> |
<%= link_to 'Delete Song', [@chart, @song], method: :delete %> |
<%= link_to 'Back To Songs', chart_song_path(@chart) %> |
<%= link_to 'Back', root_path%>
</p>